version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/usr/src/app
    environment:
      - APP_ENV=development
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
