version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app:cached  # Optimize for macOS performance
    command: ["python", "app.py"]

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: nates_db
      POSTGRES_USER: nate_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
