# Install the latest version of Bash
brew "bash"

# Install wget with IRI support
brew "wget", args: ["with-iri"]

# Install Python
brew "python"

# Install Visual Studio Code
cask "visual-studio-code"

# Install Docker
cask "docker"
